theme: jekyll-theme-architect
title-img: https://github.com/giulialiv/bggn213/blob/master/IMG_4258%20(1).jpg
title: "Giulia's Bioinformatics Class (BGGN213, Fall 2019)"
title-separator: "-"
timezone: "America/Vancouver"
highlighter: rouge
name: Giulia Livrizzi
email: "gilivriz@ucsd.edu"
avatar: "https://repository-images.githubusercontent.com/219066159/46daaf80-19ea-11ea-962c-b69680e746e2"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
