theme: jekyll-theme-architect
logo: https://bioboot.github.io/bimm143_F18/assets/img/logo.png
title: "Giulia's Bioinformatics Class (BGGN213, Fall 2019)"
highlighter: rouge
name: Giulia Livrizzi
email: "gilivriz@ucsd.edu"
avatar: "https://repository-images.githubusercontent.com/219066159/46daaf80-19ea-11ea-962c-b69680e746e2"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
